#!/bin/bash
#SBATCH --nodes=$1
#SBATCH --time=00:05:00
#SBATCH --partition=dev_multiple
#SBATCH --ntasks-per-node=$2
#SBATCH --mail-user=jonas.burster@gmail.com
#SBATCH --mail-type=END,FAIL
#SBATCH --output=slurm.out
#SBATCH --error=slurm.err
echo "Loading Pythona module and mpi module"
module load devel/python/3.10.0_gnu_11.1
module load compiler/gnu/12.1
module load mpi/openmpi/4.1
module list
startexe="mpirun --bind-to core --map-by core -report-bindings python3 ./m7.py"
exec $startexe